### ISSUE TITLE
Installation Issue on Windows 10 Anaconda Python

### ISSUE THREAD

**Issue by vrst37** [nfcpy/nfcpy#109] opened 2018-05-15 01:22 UTC
Hello, I am running into an issue on Windows 10. I am not able to determine the problem here. Can anyone point me to the right direction?

    (p2) λ python -m nfc
    Traceback (most recent call last):
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\runpy.py", line 163, in _run_module_as_main
        mod_name, _Error)
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\runpy.py", line 111, in _get_module_details
        __import__(mod_name)  # Do not catch exceptions initializing package
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\nfc\__init__.py", line 22, in <module>
        from . import clf                                                  # noqa: F401
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\nfc\clf\__init__.py", line 25, in <module>
        from . import device
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\nfc\clf\device.py", line 32, in <module>
        from . import transport
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\nfc\clf\transport.py", line 31, in <module>
        import usb1 as libusb
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\usb1\__init__.py", line 61, in <module>
        from . import libusb1
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\usb1\libusb1.py", line 199, in <module>
        libusb = _loadLibrary()
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\site-packages\usb1\libusb1.py", line 173, in _loadLibrary
        return dll_loader('libusb-1.0' + suffix, **loader_kw)
      File "C:\Users\asaxena\Miniconda3\envs\p2\lib\ctypes\__init__.py", line 366, in __init__
        self._handle = _dlopen(self._name, mode)
    WindowsError: [Error 193] %1 is not a valid Win32 application

I did all the steps as described in the documentation. What is this error? I am running windows 10 64 bit and the anaconda python is also 64bit.

    (p2) λ python
    Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:09) [MSC v.1500 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.

In the folder "C:\Windows\SysWOW64" there is a dll names libusb-1.0.dll (extracted from the libusb for windows).

Here is a list of all the packages installed currently:

    (p2) λ conda list
    packages in environment at C:\Users\asaxena\Miniconda3\envs\p2:
    Name                    Version                   Build  Channel
    certifi                   2018.4.16                py27_0
    libusb1                   1.6.4                     <pip>
    ndeflib                   0.3.2                     <pip>
    nfcpy                     0.13.4                    <pip>
    pip                       10.0.1                   py27_0
    pyDes                     2.0.1                     <pip>
    pynfc                     0.0.4                     <pip>
    pyserial                  3.4                       <pip>
    python                    2.7.15               he216670_0
    pyusb                     1.0.2                     <pip>
    setuptools                39.1.0                   py27_0
    swig                      3.0.12               h5a33001_3
    vc                        9                    h7299396_1
    vs2008_runtime            9.00.30729.1         hfaea7d5_1
    wheel                     0.31.0                   py27_0
    wincertstore              0.2              py27hf04cefb_0

**Comment by nehpetsde** [comment] 2018-05-18 18:38
Duplicate of #101

**Closed by nehpetsde** 2018-05-18 18:38 UTC
